version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependencias (incluyendo devDependencies)..."
      - npm install --production=false

  build:
    commands:
      - echo "Ejecutando build de Vite..."
      - npm run build
      - echo "Preparando carpeta de despliegue..."
      - rm -rf deploy || true
      - mkdir -p deploy
      - cp -r dist deploy/               # copia la carpeta 'dist' entera (deploy/dist)
      - cp package.json deploy/
      - cp server.js deploy/
      - ls -la deploy
      - ls -la deploy/dist

artifacts:
  files:
    - '**/*'
  base-directory: deploy
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
