
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependencias (incluyendo devDependencies)..."
      - npm install --production=false

  build:
    commands:
      - echo "Ejecutando build de Vite..."
      - npm run build
      - echo "Preparando carpeta de despliegue..."
      - rm -rf deploy || true
      - mkdir deploy
      - cp -r dist/* deploy/
      - cp package.json deploy/
      - cp server.js deploy/
      - # opcional: incluye otros archivos que necesite tu app
      - ls -la deploy

artifacts:
  files:
    - '**/*'
  base-directory: deploy

cache:
  paths:
    - node_modules/**/*
