phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependencias (incluyendo devDependencies)..."
      - npm install --production=false
  build:
    commands:
      - echo "Construyendo proyecto..."
      - npm run build

