// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyiwqvnfbswuqjkjpkju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5aXdxdm5mYnN3dXFqa2pwa2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTA4MDcsImV4cCI6MjA2OTE4NjgwN30.z4M81wcHffyQRXzRpK1jeUKE91m3_wD9oVsLUWebFLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});